name: backend CI pipeline 
on:
  push:
    branches:
      - "**"

jobs:
  packer-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_SP_CREDENTIALS}}

      - name: packer build 
        run: |
          export "NAME=${GITHUB_SHA}" 
          echo $NAME
        #  packer build -var 'github-sha=$GITHUB_SHA'app-image.json