name: backend API continuous deployment 
on:
  push:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - "**"
    types:
      - closed 

jobs:
  deploy_api:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_SP_CREDENTIALS}}
      
      - name: running packer build 
        run: |
          export "NAME=${GITHUB_SHA}"
          packer build -var 'github-sha=$NAME' app-image.json
# will need to run packer build here but, these are the commands that will be needed to run in order to get the image ID 
      - name: packer build 
        run: |
          GETID="$(az image list | jq -r '.[] | select(.name==$NAME) | .id')"
          imageid="$GETID"
          echo $imageid
          az vmss update --name test-vm --resource-group express-js-vmss --set virtualMachineProfile.storageProfile.imageReference.id=$imageid
 
          
