name: backend API continuous deployment 
on:
  push:
  pull_request:
    paths:
      - "backend/**"
    branches:
      - "main"
    types:
      - closed 

env:
  AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  AZURE_SUB_ID: ${{secrets.AZURE_SUB_ID}}
  PR_NUMBER: ${{github.event.number}}

jobs:
  deploy_api:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest


    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_SP_CREDENTIALS}}
      
      - name: running packer build 
        run: |
          NAME=${PR_NUMBER}
          packer build -var 'github-sha=$NAME' app-image.json
# will need to run packer build here but, these are the commands that will be needed to run in order to get the image ID 

      - name: trigger rolling deployment
        run: |
           NAME="prod-api-${PR_NUMBER}"
           GETID="$(az image list | jq -r '.[] | select(.name=='\"$NAME\"') | .id')"
           imageid="$GETID"
           echo $imageid
           az vmss update --name api-vmss --resource-group mern-app --set virtualMachineProfile.storageProfile.imageReference.id=$imageid
 
          
