name: backend CI pipeline 
on:
  push:
    paths:
      - "backend/**"
    branches:
      - "!main"
      - "**"

jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
      
      - name: running packer validate 
        run: |
          packer validate app-image.json
    
      - name: trigger rolling deployment
        run: |
          export NAME="prod-api-${GITHUB_SHA}"
          echo $NAME
          GETID="$(az image list | jq -r '.[] | select(.name=="$NAME") | .id')"
          imageid="$GETID"
          echo $imageid
        #  az vmss update --name api-vmss --resource-group mern-app --set virtualMachineProfile.storageProfile.imageReference.id=$imageid
      

  