name: backend CI pipeline 
on:
  push:
    paths:
      - "backend/**"
    branches:
      - "**"
      - "!main"

env:
  PR: "dev"

jobs:
  packer-build:
    runs-on: ubuntu-latest
      
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      
      - name: setup packer
        uses: hashicorp/setup-packer@main
        with:
          version: latest
    
      - name: running packer validate 
        working-directory: ./packer
        run: |
          packer validate app-image.json
          packer validate frontend-image.json
      
      
    
      

  