name: deploy application
on:
  pull_request:
    branches:
      - main 
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: deploy application 
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEB_APP_TOKEN}}
          app_location: "./frontend/"
          output_location: "./frontend/build"
          app_build_command: "npm run build"