name: deploy application
on:
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main 
    types:
      - closed


jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_SP_CREDENTIALS}}
    
      - name: login to ACR 
        uses: azure/docker-login@v1
        with:
          login-server: mernvmss.azurecr.io 
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}
    
      - name: building the docker image 
        run: | 
          docker build -f Dockerfile.prod -t mernvmss.azurecr.io/mern-frontend:${{github.sha}}
          docker push mernvmss.azurecr.io/mern-frontend:${{github.sha}}
      
      - name: roll out new version of frontend
        uses: azure/aci-deploy@v1
        with:
          resource-group: mern-app
          image: mernvmss.azurecr.io/mern-frontend:${{github.sha}}
          registry-login-server: mernvmss.azurecr.io
          registry-username: ${{secrets.ACR_USERNAME}}
          registry-password: ${{secrets.ACR_PASSWORD}}
          name: mern-frontend1
          location: 'eastus'