name: azure static web app deployment 

on:
  push:
    branches:
      - main 


jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: test
        run: ls -la
      
      - name: test again
        run: cd /home/runner/work/mern-azure-vmss/mern-azure-vmss/frontend && ls -la

      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    
  
        
        