name: azure static web app deployment 

on:
  push:
    branches:
      - main 
  pull_request:
    types: closed
    branches: 
      - main

jobs:
  build_job:
    if: github.event_name == 'push' && github.event_name != 'pull_request'
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./frontend
    name: build application
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      
      - name: show everything in the directory
        run: ls -la

      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
  
        
        