name: azure static web app deployment 

on:
  push:
    branches:
      - main 
  pull_request:
    types: closed
    branches: 
      - main


jobs:
  build_job:
    if: github.event_name == 'push' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: build application
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: listing
        run: ls -la

      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    
      - name: install dependencies
        run: cd frontend && npm install 
      
      - name: run a build 
        run: cd frontend && npm run build
  
        
        