name: azure static web app deployment 

on:
  push:
    branches:
      - main 
  pull_request:
    types: closed
    branches: 
      - main


jobs:
  build_job:
    if: github.event_name == 'push' && github.event_name != 'pull_request'
    runs-on: ubuntu-18.04
    name: build application
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      
      - name: install extras 
        run: sudo apt-get install libssl1.0-dev nodejs-dev node-gyp npm -y
      
      - name: install dependencies
        run: npm install 
        working-directory: frontend
      
      - name: run a build 
        run: npm run build 
        working-directory: frontend
  
        
        