name: azure static web app deployment 

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - "**"
      - "!main"


jobs:
  build_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
    
      - name: install dependencies
        run:  npm install 
        
      
      - name: run a build 
        run:  npm run build
      



  
        
        