name: test
on:
  pull_request:
    branches: 
      - "**"

env:
  PR_NUMBER: ${{github.event.number}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: | 
          NAME=${PR_NUMBER}
          echo $NAME